spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.1.109:1521:orcl
    username: rtkts
    password: rtk123abc
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      minimum-idle: 5 # 最小空闲连接，默认值10
      idle-timeout: 600000 # 空闲连接超时时间，默认值600000（10分钟）
      maximum-pool-size: 150 #最大连接数

mybatis:
  configuration:
    jdbc-type-for-null: null
  mapper-locations: classpath*:/mapping/**/*Mapper.xml
